/*
 * GPIO_map.c
 *
 *  Created on: 15 oct. 2017
 *      Author: Iván
 */

#include "common.h"
#include "GPIO.h"


const tGPIOInstanceMap GPIOInstanceMap[NUM_OF_GPIO] =
{
		/* {Port, GPIO_pins, GPIO_mode, GPIO_speed, GPIO_pull, GPIO_AF, GPIO_Init_Value }
		 *
		 * Port 			--> GPIOA, GPIOB, GPIOC, GPIOD, GPIOH
		 * GPIO_pins  		--> GPIO_PIN_X
		 * GPIO_mode 		--> GPIO_MODE_INPUT, GPIO_MODE_OUTPUT_PP, GPIO_MODE_OUTPUT_OD, GPIO_MODE_AF_PP,
		 * 						GPIO_MODE_AF_OD, GPIO_MODE_ANALOG
		 * GPIO_speed 		--> GPIO_SPEED_LOW, GPIO_SPEED_MEDIUM, GPIO_SPEED_FREQ_HIGH
		 * GPIO_pull 		--> GPIO_NOPULL, GPIO_PULLUP, GPIO_PULLDOWN
		 * GPIO_AF		-->
		 * GPIO_Init_Value 	--> GPIO_LOW, GPIO_HIGH, GPIO_TOGGLE, GPIO_DEFAULT        */

	/* UART1 */
			/* USART1_TX				*/ 				{ GPIOA, GPIO_PIN_9, GPIO_MODE_AF_PP, GPIO_SPEED_HIGH, GPIO_PULLUP, GPIO_AF1_USART1 , GPIO_DEFAULT },
			/* USART1_RX				*/ 				{ GPIOA, GPIO_PIN_10, GPIO_MODE_AF_PP, GPIO_SPEED_HIGH, GPIO_PULLUP, GPIO_AF1_USART1 , GPIO_DEFAULT },
	/* UART2 */
			/* USART2_TX				*/ 				{ GPIOA, GPIO_PIN_2, GPIO_MODE_AF_PP, GPIO_SPEED_HIGH, GPIO_PULLUP, GPIO_AF1_USART2 , GPIO_DEFAULT },
			/* USART2_RX				*/ 				{ GPIOA, GPIO_PIN_3, GPIO_MODE_AF_PP, GPIO_SPEED_HIGH, GPIO_PULLUP, GPIO_AF1_USART2 , GPIO_DEFAULT },

	/* LEDS */
			/* GPIO_LED_3				*/				{ GPIOC, GPIO_PIN_9, GPIO_MODE_OUTPUT_PP, GPIO_SPEED_FREQ_HIGH, GPIO_NOPULL, GPIO_AF_NONE, GPIO_LOW },
			/* GPIO_LED_4				*/				{ GPIOC, GPIO_PIN_8, GPIO_MODE_OUTPUT_PP, GPIO_SPEED_FREQ_HIGH, GPIO_NOPULL, GPIO_AF_NONE, GPIO_LOW },

	/* BUTTON */
			/* USER_BUTTON_B1			*/				{ GPIOA, GPIO_PIN_0, GPIO_MODE_INPUT, GPIO_SPEED_HIGH, GPIO_PULLDOWN, GPIO_AF_NONE, GPIO_DEFAULT },
	/* GENERAL PURPOSE */
			/* GPIO_1 					*/ 				{ GPIOA, GPIO_PIN_6, GPIO_MODE_OUTPUT_PP, GPIO_SPEED_HIGH, GPIO_AF_NONE, GPIO_DEFAULT }
};

